### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by manwinder123** [wadsworj/rogue#1]
`A Rogue/Net Hack clone built in C with the NCurses library. Code to follow rogue tutorial that I have been posting on YoutTube.`

Should be 
`A Rogue/Net Hack clone built in C with the NCurses library. Code to follow rogue tutorial that I have been posting on YouTube.`

Correction: YoutTube -> YouTube
 👍

**Comment by wadsworj** [comment]
oh snaaaaaap
